version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: psg01
    restart: always
    environment:
      POSTGRES_USER: dev-user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev_db
    ports:
      - "5432:5432"
    expose:
      - "5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "postgres", "-p", "5432", "-U", "dev-user", "-d", "dev_db"]
      interval: 10s
      retries: 3
    networks:
      - TestNetwork

networks:
    TestNetwork:
      driver: bridge

volumes:
    shared-data: